export type ContentType = "image" | "video" | "audio" | "text";

export type RiskLevel = "Safe" | "Low Risk" | "Medium Risk" | "High Risk";

export interface DetectedIssue {
  type: string;
  description: string;
  severity: "low" | "medium" | "high" | "critical";
  location?: string;
}

export interface Recommendation {
  action: string;
  priority: "low" | "medium" | "high";
}

export interface AnalysisResult {
  contentType: ContentType;
  riskScore: number;
  riskLevel: RiskLevel;
  detectedIssues: DetectedIssue[];
  recommendations: Recommendation[];
  report: string;
  analyzedAt: Date;
  fileName?: string;
}

function getRiskLevel(score: number): RiskLevel {
  if (score <= 20) return "Safe";
  if (score <= 45) return "Low Risk";
  if (score <= 70) return "Medium Risk";
  return "High Risk";
}

const IMAGE_DETECTIONS = [
  { type: "weapon", description: "Potential weapon detected in image", severity: "critical" as const },
  { type: "violence", description: "Violent imagery detected", severity: "high" as const },
  { type: "explicit", description: "Potentially explicit content", severity: "high" as const },
  { type: "blood", description: "Blood or gore detected", severity: "medium" as const },
  { type: "safe", description: "No issues detected", severity: "low" as const },
];

const TEXT_DETECTIONS = [
  { type: "hate_speech", description: "Hate speech detected", severity: "critical" as const },
  { type: "harassment", description: "Harassing language detected", severity: "high" as const },
  { type: "violent_language", description: "Violent language or threats", severity: "high" as const },
  { type: "profanity", description: "Strong profanity detected", severity: "medium" as const },
  { type: "safe", description: "No toxic language detected", severity: "low" as const },
];

const RECOMMENDATIONS_MAP: Record<string, Recommendation[]> = {
  weapon: [
    { action: "Blur or remove the detected weapon from the content", priority: "high" },
    { action: "Add a content warning disclaimer", priority: "high" },
    { action: "Consider age restriction for the post", priority: "medium" },
  ],
  violence: [
    { action: "Add a graphic content warning", priority: "high" },
    { action: "Apply blur filter to violent scenes", priority: "high" },
    { action: "Restrict content to appropriate audiences", priority: "medium" },
  ],
  hate_speech: [
    { action: "Remove or rephrase hateful language", priority: "high" },
    { action: "This content likely violates platform policies", priority: "high" },
  ],
  harassment: [
    { action: "Modify language to remove harassing content", priority: "high" },
    { action: "Consider rephrasing with respectful language", priority: "medium" },
  ],
  violent_language: [
    { action: "Remove threatening or violent language", priority: "high" },
    { action: "Add a disclaimer if discussing sensitive topics", priority: "medium" },
  ],
  profanity: [
    { action: "Consider censoring strong language", priority: "medium" },
    { action: "Be aware some platforms filter profanity", priority: "low" },
  ],
  explicit: [
    { action: "Mark content as sensitive/NSFW", priority: "high" },
    { action: "Apply age restrictions", priority: "high" },
  ],
  blood: [
    { action: "Add graphic content warning", priority: "medium" },
    { action: "Consider blurring sensitive areas", priority: "medium" },
  ],
};

function generateReport(contentType: ContentType, issues: DetectedIssue[], riskScore: number, riskLevel: RiskLevel, recommendations: Recommendation[]): string {
  const issueList = issues.length > 0 && issues[0].type !== "safe"
    ? issues.map(i => `• ${i.description}${i.location ? ` (${i.location})` : ""}`).join("\n")
    : "• No significant issues detected";

  const recList = recommendations.length > 0
    ? recommendations.map(r => `• [${r.priority.toUpperCase()}] ${r.action}`).join("\n")
    : "• Content appears safe for publishing";

  return `═══════════════════════════════════════
    CONTENT SAFETY REPORT — MindGuardAI
═══════════════════════════════════════

Content Type: ${contentType.charAt(0).toUpperCase() + contentType.slice(1)}
Risk Score: ${riskScore}%
Risk Level: ${riskLevel}

─── Detected Issues ───
${issueList}

─── Analysis ───
${riskScore > 60
    ? "The detected objects and language may indicate unsafe or violent content that could violate social media platform policies."
    : riskScore > 30
    ? "Minor issues were detected. The content may require slight modifications before publishing."
    : "The content appears generally safe for publishing on most social media platforms."}

─── Recommendations ───
${recList}

═══════════════════════════════════════
Generated by MindGuardAI Analysis Engine
${new Date().toLocaleString()}`;
}

function simulateDelay(): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, 1500 + Math.random() * 2000));
}

export async function analyzeImage(file: File): Promise<AnalysisResult> {

  const formData = new FormData();
  formData.append("file", file);

  const response = await fetch("http://127.0.0.1:5000/analyze-image", {
    method: "POST",
    body: formData
  });

  const data = await response.json();

  // Convert backend risk level to score
  let riskScore = 10;
  let riskLevel: RiskLevel = "Safe";

  if (data.risk_level === "High") {
    riskScore = 85;
    riskLevel = "High Risk";
  }
  else if (data.risk_level === "Medium") {
    riskScore = 55;
    riskLevel = "Medium Risk";
  }
  else {
    riskScore = 10;
    riskLevel = "Safe";
  }

  const issues: DetectedIssue[] = [
    {
      type: "image_detection",
      description: data.detected_issue,
      severity:
        data.risk_level === "High"
          ? "critical"
          : data.risk_level === "Medium"
          ? "medium"
          : "low"
    }
  ];

  const recommendations: Recommendation[] = [
    {
      action: data.recommendation,
      priority:
        data.risk_level === "High"
          ? "high"
          : data.risk_level === "Medium"
          ? "medium"
          : "low"
    }
  ];

  return {
    contentType: "image",
    riskScore,
    riskLevel,
    detectedIssues: issues,
    recommendations,
    report: generateReport("image", issues, riskScore, riskLevel, recommendations),
    analyzedAt: new Date(),
    fileName: file.name
  };
}

export async function analyzeVideo(file: File): Promise<AnalysisResult> {

  const formData = new FormData();
  formData.append("file", file);

  const response = await fetch("http://127.0.0.1:5000/analyze-video", {
    method: "POST",
    body: formData
  });

  const data = await response.json();

  const riskScore = data.risk_score || 20;
  const riskLevel = getRiskLevel(riskScore);

  const issues: DetectedIssue[] = [
    {
      type: "video_analysis",
      description: data.detected_issue,
      severity: riskScore > 70 ? "critical" : riskScore > 40 ? "medium" : "low"
    }
  ];

  const recommendations: Recommendation[] = [
    {
      action: data.recommendation,
      priority: riskScore > 70 ? "high" : "medium"
    }
  ];

  return {
    contentType: "video",
    riskScore,
    riskLevel,
    detectedIssues: issues,
    recommendations,
    report: generateReport("video", issues, riskScore, riskLevel, recommendations),
    analyzedAt: new Date(),
    fileName: file.name
  };
}

export async function analyzeAudio(file: File): Promise<AnalysisResult> {

  const formData = new FormData();
  formData.append("file", file);

  const response = await fetch("http://127.0.0.1:5000/analyze-audio", {
    method: "POST",
    body: formData
  });

  const data = await response.json();

  const riskScore = data.risk_score || 20;
  const riskLevel = getRiskLevel(riskScore);

  const issues: DetectedIssue[] = [
    {
      type: "audio_analysis",
      description: data.detected_issue,
      severity: riskScore > 70 ? "high" : "low"
    }
  ];

  const recommendations: Recommendation[] = [
    {
      action: data.recommendation,
      priority: riskScore > 70 ? "high" : "low"
    }
  ];

  return {
    contentType: "audio",
    riskScore,
    riskLevel,
    detectedIssues: issues,
    recommendations,
    report: generateReport("audio", issues, riskScore, riskLevel, recommendations),
    analyzedAt: new Date(),
    fileName: file.name
  };
}

export async function analyzeText(text: string): Promise<AnalysisResult> {

  const response = await fetch("http://127.0.0.1:5000/analyze-text", {
    method: "POST",
    headers: {
      "Content-Type": "application/json"
    },
    body: JSON.stringify({ text })
  });

  const data = await response.json();

  const riskScore = data.risk_level === "High" ? 85 : 20;
  const riskLevel = data.risk_level === "High" ? "High Risk" : "Low Risk";

  const issues: DetectedIssue[] = [
    {
      type: "text_analysis",
      description: data.detected_issue,
      severity: data.risk_level === "High" ? "high" : "low"
    }
  ];

  const recommendations: Recommendation[] = [
    {
      action: data.recommendation,
      priority: data.risk_level === "High" ? "high" : "low"
    }
  ];

  return {
    contentType: "text",
    riskScore,
    riskLevel,
    detectedIssues: issues,
    recommendations,
    report: generateReport("text", issues, riskScore, riskLevel, recommendations),
    analyzedAt: new Date()
  };
}